#!/bin/bash
# pickup the path of our program so we can call scripts relatively
PATH=$PATH:`dirname $0`

# check if root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root for hardware access" 1>&2
   exit 1
fi

# first try SPI EEPROM
MAC=`readMAC.25AA02E48`
if [ "$?" -eq "0" ]; then
	echo $MAC
  	exit 0
fi

# then try I2C EEPROM
MAC=`readMAC.24AA02E48`
if [ "$?" -eq "0" ]; then
	echo $MAC
  	exit 0
fi

# then go with default
echo "00:00:00:12:34:56"
exit 1
