#!/bin/bash
# pickup the path of our program so we can call scripts relatively
PATH=$PATH:`dirname $0`

# check if root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root for hardware access" 1>&2
   exit 1
fi

# see if we have an ENC28J60 network card. Only way I have figured
# out is to look in /proc/irq for an enc28j60 entry. lsmod will show
# enc28j60 as not used, even when that interface is available
IRQ=`find /proc/irq | grep enc28j60`
if [ "$?" -ne "0" ]; then
  	exit 2
fi

# first try SPI EEPROM
MAC=`readMAC.25AA02E48`
if [ "$?" -eq "0" ]; then
	echo $MAC
  	exit 0
fi

# then try I2C EEPROM
MAC=`readMAC.24AA02E48`
if [ "$?" -eq "0" ]; then
	echo $MAC
  	exit 0
fi

# then go with default
echo "00:00:00:12:34:56"
exit 1
